# https://docs.aws.amazon.com/secretsmanager/latest/userguide/integrating_csi_driver.html#integrating_csi_driver_mount
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
   name: myapp-aws-secrets
   namespace: example-8
spec:
  provider: aws
  parameters:
    region: us-east-1
    objects:
      - objectName: myapp-secret
        objectType: secretsmanager
        jmesPath: # As secret in AWS Secret Manager in JSON format, Use Jmes to extract elements from JSON
          - path: username
            objectAlisa: myusername
          - path: password
            objectAlisa: mypassword
  secretObjects: # Keep secret in K8S Secret
    - secretName: myapp-k8s-secret
      type: Opaque
      data:
        - path: myusername
          objectAlisa: k8s-myusername
        - path: mypassword
          objectAlisa: k8s-mypassword