apiVersion: v1
kind: Pod
metadata:
  name: myapp-1
  namespace: example-7
spec:
  containers:
    - name: myapp-1
      image: /myapp
      volumeMounts:
        - name: persistent-storage
          mountPath: /data
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: myapp # must match to the name in pvc