apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp
  namespace: example-7
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs
  resources:
    requests:
      storage: 5Gi # Doesn't matter as EFS is elastic