apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myapp
  namespace: example-6
spec:
  serviceName: myservice # for headless service in statefulset
  selector:
    matchLabels:
      app: myapp # has to match with .spec.template.metadata.labels
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp # has to match with .spec.selector.matchLabels
    spec:
      containers:
      - name: myapp
        image: /myapp
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: data # must match the name in volumeClaimTemplates
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: gp2
      accessModes: [ "ReadWriteOnce" ] # ReadWriteOnce: volume can by mounted as read-write by a single node, multi-pods inside the node can access the volume
      resources:
        requests:
          storage: 5Gi
