apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  ports:
    - port: 80 # Service port (access by other node WITHIN same cluster)
      targetPort: 8080 # Pod's port
      NodePort: # Node port (for external access)
  selector:
    app: my-app # labels of pods with same value to the selector will belong to this service